## 전체 64x64로 변환

In [0]:
import os
import pandas as pd
from PIL import Image
import os, glob, numpy as np
from sklearn.model_selection import train_test_split

In [0]:
dataset = pd.read_csv('E:\\Senitment_data\\csv\\face.csv', index_col = 0)
dataset

path  no gender  age  emo  light
0     E:\Senitment_data\total_jpg\000-ang-01.JPG   0      남   28    0      1
1     E:\Senitment_data\total_jpg\000-ang-02.JPG   0      남   28    0      1
2     E:\Senitment_data\total_jpg\000-ang-03.JPG   0      남   28    0      1
3     E:\Senitment_data\total_jpg\000-ang-04.JPG   0      남   28    0      1
4     E:\Senitment_data\total_jpg\000-ang-05.JPG   0      남   28    0      1
...                                          ...  ..    ...  ...  ...    ...
4901  E:\Senitment_data\total_jpg\000-dis-13.JPG   0      남   28    1      1
4902  E:\Senitment_data\total_jpg\000-dis-14.JPG   0      남   28    1      1
4903  E:\Senitment_data\total_jpg\000-fea-00.JPG   0      남   28    2      1
4904  E:\Senitment_data\total_jpg\000-fea-01.JPG   0      남   28    2      1
4905  E:\Senitment_data\total_jpg\000-ang-00.JPG   0      남   28    0      1

[4906 rows x 6 columns]

In [0]:
path_dir = 'E:\\Senitment_data\\dot_part_jpg\\mouth'
file_list = os.listdir(path_dir)
dataset = pd.DataFrame()
dataset['path'] = file_list
dataset

path
0     mouth-000-hap-01.JPG
1     mouth-000-hap-02.JPG
2     mouth-000-hap-03.JPG
3     mouth-000-hap-04.JPG
4     mouth-000-hap-05.JPG
...                    ...
4882  mouth-000-dis-06.JPG
4883  mouth-000-dis-07.JPG
4884  mouth-000-dis-08.JPG
4885  mouth-000-fea-14.JPG
4886  mouth-000-hap-00.JPG

[4887 rows x 1 columns]

In [0]:
dataset['path'] = 'E:\\Senitment_data\\dot_part_jpg\\mouth\\' + dataset['path']
dataset

path
0     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...
1     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...
2     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...
3     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...
4     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...
...                                                 ...
4882  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...
4883  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...
4884  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...
4885  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...
4886  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...

[4887 rows x 1 columns]

In [0]:
# 성별, 나이, 감정 칼럼 생성
inform = pd.read_excel('E:\\Senitment_data\\참가자정보.xlsx')
inform

번호 성별  나이
0    0  남  28
1    1  여  34
2    2  남  21
3    3  여  24
4    4  남  20
..  .. ..  ..
95  95  여  33
96  96  여  42
97  97  여  32
98  98  여  26
99  99  여  27

[100 rows x 3 columns]

In [0]:
inform.columns = ['no', 'gender', 'age']
inform

no gender  age
0    0      남   28
1    1      여   34
2    2      남   21
3    3      여   24
4    4      남   20
..  ..    ...  ...
95  95      여   33
96  96      여   42
97  97      여   32
98  98      여   26
99  99      여   27

[100 rows x 3 columns]

In [0]:
dataset['no'] = None
for i in range(0, len(dataset)) :
    dataset['no'][i] = dataset['path'][i].split('\\')[4].split('-')[1]
dataset

path   no
0     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...  000
1     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...  000
2     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...  000
3     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...  000
4     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...  000
...                                                 ...  ...
4882  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...  000
4883  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...  000
4884  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...  000
4885  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...  000
4886  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...  000

[4887 rows x 2 columns]

In [0]:
dataset['no'] = pd.to_numeric(dataset['no'])

In [0]:
dataset = pd.merge(dataset, inform.drop_duplicates(['no']), on="no", how="left")
dataset

path  no gender  age
0     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28
1     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28
2     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28
3     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28
4     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28
...                                                 ...  ..    ...  ...
4882  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28
4883  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28
4884  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28
4885  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28
4886  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28

[4887 rows x 4 columns]

In [0]:
dataset['emo'] = None
for i in range(0, len(dataset)) :
    dataset['emo'][i] = dataset['path'][i].split('\\')[4].split('-')[2]
    
dataset

C:\Users\1-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


path  no gender  age  emo
0     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28  hap
1     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28  hap
2     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28  hap
3     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28  hap
4     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28  hap
...                                                 ...  ..    ...  ...  ...
4882  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28  dis
4883  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28  dis
4884  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28  dis
4885  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28  fea
4886  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28  hap

[4887 rows x 5 columns]

In [0]:
for i in range(0, len(dataset)) :
    if dataset['emo'][i] == 'ang' :
        dataset['emo'][i] = 0
    elif dataset['emo'][i] == 'dis' :
        dataset['emo'][i] = 1
    elif dataset['emo'][i] == 'fea' :
        dataset['emo'][i] = 2
    elif dataset['emo'][i] == 'hap' :
        dataset['emo'][i] = 3
    elif dataset['emo'][i] == 'sad' :
        dataset['emo'][i] = 4
    elif dataset['emo'][i] == 'sur' :
        dataset['emo'][i] = 5
    elif dataset['emo'][i] == 'neu' :
        dataset['emo'][i] = 6
          
dataset

C:\Users\1-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\1-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\1-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\1-7\Anaconda3\lib\s

path  no gender  age emo
0     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3
1     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3
2     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3
3     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3
4     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3
...                                                 ...  ..    ...  ...  ..
4882  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   1
4883  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   1
4884  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   1
4885  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   2
4886  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3

[4887 rows x 5 columns]

In [0]:
dataset['light'] = None
for i in range(0, len(dataset)) :
    if dataset['no'][i] <= 40 :
        dataset['light'][i] = 1
    elif dataset['no'][i] > 40 :
        dataset['light'][i] = 0
dataset

C:\Users\1-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\1-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


path  no gender  age emo  \
0     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   
1     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   
2     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   
3     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   
4     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   
...                                                 ...  ..    ...  ...  ..   
4882  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   1   
4883  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   1   
4884  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   1   
4885  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   2   
4886  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   

     light  
0        1  
1        1  
2        1  
3        1  
4        1  
...    ...  
4882     1  
4883     1  
4884     1  
4885     1  
4886     1  

[4887 rows x 6 columns]

In [0]:
dataset.to_csv('E:\\Senitment_data\\csv\\dot_mouth.csv', sep=',', na_rep='NaN')

### pixel화

In [0]:
image_w = 64
image_h = 64

data = []

for i in dataset['path']:
        img = Image.open(i)
        img = img.convert("L")
        #img = img.resize(image_w * image_h)
        img = img.resize((image_w, image_h))

        img_data = np.asarray(img)

        data.append(img_data)
        
data

[array([[ 92,  95, 100, ..., 105, 101,  94],
        [ 91,  95,  99, ..., 103,  99,  92],
        [ 90,  96,  99, ..., 102,  96,  87],
        ...,
        [ 63,  66,  69, ...,  55,  62,  59],
        [ 63,  64,  68, ...,  56,  58,  59],
        [ 63,  63,  68, ...,  56,  56,  59]], dtype=uint8),
 array([[84, 91, 94, ..., 96, 89, 85],
        [85, 92, 94, ..., 95, 89, 84],
        [86, 92, 94, ..., 92, 87, 84],
        ...,
        [56, 60, 67, ..., 57, 55, 58],
        [54, 58, 67, ..., 58, 56, 57],
        [53, 56, 66, ..., 57, 57, 56]], dtype=uint8),
 array([[78, 79, 80, ..., 78, 77, 75],
        [79, 79, 80, ..., 78, 77, 75],
        [80, 79, 81, ..., 77, 77, 75],
        ...,
        [60, 64, 63, ..., 66, 68, 66],
        [60, 64, 63, ..., 66, 67, 67],
        [59, 64, 62, ..., 66, 66, 68]], dtype=uint8),
 array([[87, 92, 96, ..., 80, 80, 78],
        [88, 92, 96, ..., 80, 80, 78],
        [88, 92, 95, ..., 81, 81, 78],
        ...,
        [59, 66, 69, ..., 84, 89, 88],
        [

In [0]:
dataset['pixels'] = None

for i in range(0,len(data)):
    dataset['pixels'][i] = data[i].flatten()
    
dataset

C:\Users\1-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


path  no gender  age emo  \
0     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   
1     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   
2     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   
3     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   
4     E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   
...                                                 ...  ..    ...  ...  ..   
4882  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   1   
4883  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   1   
4884  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   1   
4885  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   2   
4886  E:\Senitment_data\dot_part_jpg\mouth\mouth-000...   0      남   28   3   

     light                                             pixels  
0        1  [92, 95, 100, 100, 102, 103, 106, 110, 109, 11...  
1        1  [84, 91, 94, 97, 96, 102, 104, 104, 106, 107, ...  
2        1  [78, 79, 80, 81, 85, 86, 88, 90, 90, 90, 90, 9...  
3        1  [87, 92, 96, 100, 103, 106, 106, 106, 109, 108...  
4        1  [92, 93, 94, 98, 99, 100, 105, 103, 106, 106, ...  
...    ...                                                ...  
4882     1  [83, 86, 91, 95, 98, 100, 101, 102, 103, 106, ...  
4883     1  [78, 82, 91, 91, 95, 97, 97, 99, 104, 102, 106...  
4884     1  [107, 108, 110, 112, 109, 109, 110, 110, 112, ...  
4885     1  [78, 78, 85, 89, 94, 98, 97, 101, 106, 106, 10...  
4886     1  [70, 72, 75, 82, 86, 86, 88, 91, 91, 90, 92, 9...  

[4887 rows x 7 columns]

In [0]:
data = dataset['pixels']

In [0]:
from tensorflow.keras.utils import to_categorical

In [0]:
labels_one_hot = to_categorical(dataset['emo'])
labels_one_hot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
y_df_train = labels_one_hot
X_df_train = data

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X_df_train, y_df_train,
                                                    stratify = y_df_train,
                                                    test_size=0.1, random_state=1234)

In [0]:
#np.vstack stack arrays in sequence vertically (picking element row wise)
X_train = np.vstack(X_train)
X_test = np.vstack(X_test)

#Reshape X_train, y_train,X_test,y_test in desired formats
X_train = np.reshape(X_train, (X_train.shape[0],64,64,1))
# y_train = np.reshape(y_train, (y_train.shape[0],1))
X_test = np.reshape(X_test, (X_test.shape[0],64,64,1))
# y_test = np.reshape(y_test, (y_test.shape[0],1))

print("Shape of X_train and y_train is " + str(X_train.shape) +" and " + str(y_train.shape) +" respectively.")
print("Shape of X_test and y_test is " + str(X_test.shape) +" and " + str(y_test.shape) +" respectively.")

Shape of X_train and y_train is (4398, 64, 64, 1) and (4398, 7) respectively.
Shape of X_test and y_test is (489, 64, 64, 1) and (489, 7) respectively.


In [0]:
np.save('E:\\Senitment_data\\train_test\\dot_mouth\\X_train.npy', X_train) 
np.save('E:\\Senitment_data\\train_test\\dot_mouth\\y_train.npy', y_train) 
np.save('E:\\Senitment_data\\train_test\\dot_mouth\\X_test.npy', X_test) 
np.save('E:\\Senitment_data\\train_test\\dot_mouth\\y_test.npy', y_test) 